uploads = []

[[generated]]
id = "JUL-2QqrcPL_5GHpuUeZL"
uri = "file://artifacts/landing/public/hero-app.png"
type = "image"
title = "Sleek mobile app mockup"

[[generated]]
id = "Qg2S0afJAkgsIZKmH3dQ0"
uri = "file://artifacts/landing/public/closet.png"
type = "image"
title = "Modern minimalist closet"

[[generated]]
id = "xrjo6QpIb8u5nQ-2VHcky"
uri = "file://artifacts/landing/public/confident-walk.png"
type = "image"
title = "Confident stylish person"

[[outputs]]
id = "CmjwW9T-vMC5BR4rZwT-c"
uri = "file://fitcheck-source.zip"
type = "unspecified"
title = "FIT✔️ Full Source Code"

[[outputs]]
id = "Ge6lmVdS-ogOU-u8ls2Av"
uri = "file://cert_key.tar.gz"
type = "unspecified"
title = "Distribution Certificate Private Key (cert_key.pem inside)"
