// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/grwm-cam/FitCheckCam.tsx": () => import("../components/mockups/grwm-cam/FitCheckCam.tsx"),
  "./components/mockups/themes/AmberElevated.tsx": () => import("../components/mockups/themes/AmberElevated.tsx"),
  "./components/mockups/themes/AuroraMinimal.tsx": () => import("../components/mockups/themes/AuroraMinimal.tsx"),
  "./components/mockups/themes/DarkObsidian.tsx": () => import("../components/mockups/themes/DarkObsidian.tsx")
};
